modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory
issueTrackerURL="https://github.com/caltinor" #optional
displayURL="https://github.com/caltinor" #optional
logoFile="" #optional
credits="Thanks to the MMD community." #optional
authors="Caltinor" #optional
license="ARR License"

[[mods]] #mandatory
modId="dicemcmm" #mandatory
version="${file.jarVersion}"
displayName="Money and Sign Shops"
#updateJSONURL=""
description='''
A server side money mod with sign-shops.
'''

[[dependencies.dicemcmm]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41.0.1,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dicemcmm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
